### ISSUE TITLE
All of the ABC_News_Politics jsons are empty

### ISSUE THREAD

**Issue by gabefair** [gsantia/BuzzFace#1]
Thank you for providing this dataset! Wonderful talk today.

`attach.json` is blank. 2 bytes
`posts.json` is 22 bytes with the following content. `{"reacts": null}`
`comment.json` is blank. 2 bytes

I made sure the facebook app was `live` before I ran the script.
I am on the free tier of Disqus. Do I need to be on the pro tier?

**Comment by gabefair** [comment]
It seems that the script does not know when I've hit my rate limit
![image](https://user-images.githubusercontent.com/2096785/42067227-1ed7f44c-7b13-11e8-9162-79036a0a4cd4.png)

**Comment by gabefair** [comment]
So it seems like there isn't a way to pay to increase facebook's api limit. How did you get the data, is there a way around it? Also you can PM me on [keybase.io/gabefair](http://keybase.io/gabefair)

**Comment by gsantia** [comment]
Hi Gabe,

Thanks for flagging this. Apologies for the delayed reply, but it's only been recently that we were able to determine the exact specifications of Facebook's new API rate limit. The code was written under the old limit of about 3600 calls / hour, but now it seems it's 200 / hour.  This marks the fourth (!!!!) time we've had to rewrite code since the project's inception due to a change in the Graph API. 

We'll be in touch once the code has been modified to respect the new rate limit. 

Cheers

**Comment by gsantia** [comment]
Ok, I'm under the impression that it's been fixed now. 
Unfortunately, due to this extreme cut to the rate limit, I removed the querying of
the top-level comments for replies, as each of these counts as an API call, which would make
this script now take a very long time to run (since the new limit requires us to wait about 20 seconds
in between calls). If you'd like to wait, I left instructions in `threaded_comments.json` on how to switch it back.

Please let me know if there are still problems getting the data set to download!

Thanks
